"""accounts.tests: tests for the login, logout and activation redirect.

Run with:
    docker compose exec web python manage.py test accounts -v 2
"""
import os
from io import StringIO
from unittest.mock import patch

from django.core.management import CommandError, call_command
from django.test import TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from accounts.forms import GENERIC_LOGIN_ERROR
from accounts.models import ArchiveReason, Extension, Role, Status, User
from audit.models import AuditLog

PASSWORD = "correct-horse-battery"


def make_user(**overrides):
    """Create an active member with a known password.

    Created through create_user() so account_id is generated by User.save().
    Pass keyword arguments to override any field (status, email, ...).
    """
    extension = Extension.objects.get_or_create(name="Test Extension")[0]
    fields = dict(
        first_name="Juan",
        last_name="Dela Cruz",
        role=Role.MEMBER,
        extension=extension,
        status=Status.ACTIVE,
        must_change_password=False,
    )
    fields.update(overrides)
    return User.objects.create_user(password=PASSWORD, **fields)


class LoginTests(TestCase):
    """Behaviour of POST /login/."""

    def setUp(self):
        self.url = reverse("accounts:login")

    def post(self, identifier, password=PASSWORD, **extra):
        """Submit the login form."""
        return self.client.post(
            self.url, {"identifier": identifier, "password": password, **extra}
        )

    def test_login_with_account_id(self):
        user = make_user()
        response = self.post(user.account_id)
        self.assertRedirects(response, "/", fetch_redirect_response=False)
        self.assertEqual(int(self.client.session["_auth_user_id"]), user.pk)

    def test_login_with_verified_email_is_case_insensitive(self):
        make_user(email="juan@example.com", email_verified_at=timezone.now())
        response = self.post("JUAN@Example.com")
        self.assertRedirects(response, "/", fetch_redirect_response=False)

    def test_unverified_pending_email_cannot_log_in(self):
        make_user(pending_email="juan@example.com")
        response = self.post("juan@example.com")
        self.assertContains(response, GENERIC_LOGIN_ERROR)
        self.assertNotIn("_auth_user_id", self.client.session)

    def test_wrong_password_and_unknown_account_show_the_same_message(self):
        user = make_user()
        wrong_password = self.post(user.account_id, password="nope")
        unknown_account = self.post("99999999")
        self.assertContains(wrong_password, GENERIC_LOGIN_ERROR)
        self.assertContains(unknown_account, GENERIC_LOGIN_ERROR)

    def test_badly_shaped_identifier_shows_the_same_message(self):
        response = self.post("not-an-id")
        self.assertContains(response, GENERIC_LOGIN_ERROR)

    def test_archived_account_is_denied_with_the_same_message(self):
        user = make_user(
            status=Status.ARCHIVED,
            archived_at=timezone.now(),
            archive_reason=ArchiveReason.MANUAL,
        )
        response = self.post(user.account_id)
        self.assertContains(response, GENERIC_LOGIN_ERROR)
        self.assertNotIn("_auth_user_id", self.client.session)

    def test_not_activated_user_goes_to_activation(self):
        user = make_user(status=Status.NOT_ACTIVATED)
        response = self.post(user.account_id)
        self.assertRedirects(
            response, reverse("accounts:activate"), fetch_redirect_response=False
        )

    def test_must_change_password_user_goes_to_activation(self):
        user = make_user(must_change_password=True)
        response = self.post(user.account_id)
        self.assertRedirects(
            response, reverse("accounts:activate"), fetch_redirect_response=False
        )

    def test_safe_next_url_is_followed(self):
        user = make_user()
        response = self.post(user.account_id, next="/prayer/")
        self.assertRedirects(response, "/prayer/", fetch_redirect_response=False)

    def test_external_next_url_is_ignored(self):
        user = make_user()
        response = self.post(user.account_id, next="https://evil.example.com/")
        self.assertRedirects(response, "/", fetch_redirect_response=False)

    def test_logged_in_user_skips_the_form(self):
        user = make_user()
        self.client.force_login(user)
        response = self.client.get(self.url)
        self.assertRedirects(response, "/", fetch_redirect_response=False)


class LoginAuditTests(TestCase):
    """Failed logins are logged, and never with a password."""

    def setUp(self):
        self.url = reverse("accounts:login")

    @patch("accounts.services.log_action")
    def test_wrong_password_is_logged_without_secrets(self, log_action):
        user = make_user()
        self.client.post(
            self.url, {"identifier": user.account_id, "password": "secret-guess"}
        )
        log_action.assert_called_once()
        logged = repr(log_action.call_args)
        self.assertIn("bad_password", logged)
        self.assertNotIn("secret-guess", logged)

    @patch("accounts.services.log_action")
    def test_unknown_account_is_logged_without_the_typed_text(self, log_action):
        self.client.post(self.url, {"identifier": "99999999", "password": "x"})
        log_action.assert_called_once()
        logged = repr(log_action.call_args)
        self.assertIn("unknown_account", logged)
        self.assertNotIn("99999999", logged)

    def test_real_audit_row_is_written_for_a_failed_login(self):
        user = make_user()
        self.client.post(
            self.url,
            {"identifier": user.account_id, "password": "secret-guess"},
            REMOTE_ADDR="203.0.113.9",
        )
        row = AuditLog.objects.get(action="account.login_failed")
        self.assertEqual(row.status, AuditLog.Result.FAILED)
        self.assertEqual(row.entity_id, user.pk)
        self.assertEqual(row.extension_id, user.extension_id)
        self.assertEqual(row.after, {"reason": "bad_password"})
        self.assertEqual(row.ip_address, "203.0.113.9")
        self.assertIsNone(row.actor_id)  # nobody was logged in

    @patch("accounts.services.log_action")
    def test_successful_login_is_not_logged_as_a_failure(self, log_action):
        user = make_user()
        self.client.post(self.url, {"identifier": user.account_id, "password": PASSWORD})
        log_action.assert_not_called()


class LogoutTests(TestCase):
    """Logout is POST-only."""

    def test_get_is_rejected(self):
        self.client.force_login(make_user())
        response = self.client.get(reverse("accounts:logout"))
        self.assertEqual(response.status_code, 405)
        self.assertIn("_auth_user_id", self.client.session)

    def test_post_logs_out(self):
        self.client.force_login(make_user())
        response = self.client.post(reverse("accounts:logout"))
        self.assertRedirects(
            response, reverse("accounts:login"), fetch_redirect_response=False
        )
        self.assertNotIn("_auth_user_id", self.client.session)


@override_settings(DEBUG=True)  # the test runner forces DEBUG off, so turn it back on
class SeedSuperadminTests(TestCase):
    """The seed_superadmin management command."""

    def run_command(self, **env):
        """Run the command with the given environment values; return its output."""
        out = StringIO()
        with patch.dict(os.environ, env):
            call_command("seed_superadmin", stdout=out)
        return out.getvalue()

    def test_creates_a_working_super_admin(self):
        output = self.run_command(SEED_SUPERADMIN_PASSWORD=PASSWORD)
        user = User.objects.get(role=Role.SUPER_ADMIN)
        self.assertIn(user.account_id, output)
        self.assertTrue(user.check_password(PASSWORD))
        self.assertEqual(user.status, Status.ACTIVE)
        self.assertFalse(user.must_change_password)

    def test_running_twice_does_not_create_a_second_one(self):
        self.run_command(SEED_SUPERADMIN_PASSWORD=PASSWORD)
        self.run_command(SEED_SUPERADMIN_PASSWORD=PASSWORD)
        self.assertEqual(User.objects.filter(role=Role.SUPER_ADMIN).count(), 1)

    def test_requires_a_password(self):
        with patch.dict(os.environ, {"SEED_SUPERADMIN_PASSWORD": ""}):
            with self.assertRaises(CommandError):
                call_command("seed_superadmin", stdout=StringIO())

    @override_settings(DEBUG=False)
    def test_refuses_to_run_outside_debug(self):
        with self.assertRaises(CommandError):
            self.run_command(SEED_SUPERADMIN_PASSWORD=PASSWORD)