# Generated by Django 6.1.1 on 2026-10-05 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('verse_date', models.DateField(primary_key=True, serialize=False)),
                ('translation', models.CharField(choices=[('ESV', 'ESV'), ('MBBTAG', 'MBB (Tagalog)')], max_length=10)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.PositiveIntegerField()),
                ('verse_start', models.PositiveIntegerField()),
                ('verse_end', models.PositiveIntegerField(blank=True, null=True)),
                ('verse_text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'daily_verse',
                'constraints': [models.CheckConstraint(condition=models.Q(('verse_end__isnull', True), ('verse_end__gte', models.F('verse_start')), _connector='OR'), name='daily_verse_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='BibleChapterRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(choices=[('ESV', 'ESV'), ('MBBTAG', 'MBB (Tagalog)')], max_length=10)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.PositiveIntegerField()),
                ('read_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_chapter_read',
                'constraints': [models.UniqueConstraint(fields=('user', 'translation', 'book', 'chapter', 'read_date'), name='uq_bible_chapter_read')],
            },
        ),
    ]
