# Generated by Django 6.1.1 on 2026-10-05 01:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='ThemePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=5)),
                ('color_primary', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_primary_hover', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_primary_soft', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_bg', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_surface', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_surface_alt', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_txt_primary', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_txt_secondary', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_txt_muted', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_border', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_border_strong', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_success', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_error', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_warning', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_info', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_accent', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_accent_hover', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('color_accent_soft', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex colour.')])),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='theming.theme')),
            ],
            options={
                'db_table': 'theme_palette',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('color_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'Follow device')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('fil', 'Filipino')], default='en', max_length=3)),
                ('mobile_nav_style', models.CharField(choices=[('bottom', 'Bottom bar'), ('hamburger', 'Hamburger menu')], default='bottom', max_length=10)),
                ('event_reminders_enabled', models.BooleanField(default=True)),
                ('event_reminder_minutes', models.PositiveIntegerField(default=1440, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(43200)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='theming.theme')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uq_theme_default'),
        ),
        migrations.AddConstraint(
            model_name='themepalette',
            constraint=models.UniqueConstraint(fields=('theme', 'mode'), name='uq_theme_palette_mode'),
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.CheckConstraint(condition=models.Q(('event_reminder_minutes__lte', 43200)), name='reminder_minutes_max'),
        ),
    ]
