# Generated by Django 6.1.1 on 2026-10-08 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='defaultpassword',
            name='uq_default_password',
        ),
        migrations.AddField(
            model_name='defaultpassword',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_passwords', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='defaultpassword',
            constraint=models.UniqueConstraint(fields=('owner', 'applies_to_role'), name='uq_default_password'),
        ),
        migrations.RemoveField(
            model_name='defaultpassword',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='defaultpassword',
            name='set_by',
        ),
    ]
