# Generated by Django 6.1.2 on 2026-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_default_password_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpassword',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
