# Generated by Django 6.1.1 on 2026-10-05 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_setting',
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('entity_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('purge_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('purge_after_days__isnull', True), ('purge_after_days__gt', 0), _connector='OR'), name='retention_days_positive')],
            },
        ),
    ]
