# Generated by Django 6.1.1 on 2026-10-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('completed', 'Completed'), ('archived', 'Archived')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prayer_requests', to='accounts.extension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_request',
            },
        ),
        migrations.CreateModel(
            name='PrayerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='prayer.prayerrequest')),
            ],
            options={
                'db_table': 'prayer_reply',
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['coordinator', 'status'], name='ix_prayer_coord_status'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['extension', 'status'], name='ix_prayer_ext_status'),
        ),
        migrations.AddConstraint(
            model_name='prayerrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='prayer_archived_matches_status'),
        ),
    ]
