# Generated by Django 6.1.1 on 2026-10-05 01:54

import accounts.models
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('building_number', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('barangay', models.CharField(blank=True, max_length=150)),
                ('municipality', models.CharField(default='Santa Rosa', max_length=150)),
                ('province', models.CharField(default='Nueva Ecija', max_length=150)),
                ('country', models.CharField(default='Philippines', max_length=150)),
                ('postal_code', models.CharField(default='3101', max_length=10)),
            ],
            options={
                'db_table': 'extension',
            },
        ),
        migrations.CreateModel(
            name='SpecialRole',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'special_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('role', models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('coordinator', 'Coordinator'), ('member', 'Member')], max_length=20)),
                ('status', models.CharField(choices=[('not_activated', 'Not activated'), ('active', 'Active'), ('archived', 'Archived')], default='not_activated', max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('last_attended_at', models.DateField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, choices=[('manual', 'Manual'), ('inactive', 'Inactive')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='accounts.extension')),
            ],
            options={
                'db_table': 'app_user',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_extensions', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to='accounts.user')),
            ],
            options={
                'db_table': 'email_token',
            },
        ),
        migrations.CreateModel(
            name='DefaultPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to_role', models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('member', 'Member')], max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_passwords', to='accounts.extension')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
            ],
            options={
                'db_table': 'default_password',
            },
        ),
        migrations.CreateModel(
            name='UserExtensionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('manual', 'Manual'), ('auto_transfer', 'Auto transfer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.extension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_history', to='accounts.user')),
            ],
            options={
                'db_table': 'user_extension_history',
            },
        ),
        migrations.CreateModel(
            name='UserSpecialRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_role_holders', to='accounts.extension')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='accounts.specialrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_roles', to='accounts.user')),
            ],
            options={
                'db_table': 'user_special_role',
            },
        ),
        migrations.CreateModel(
            name='ExtensionSpecialRoleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.PositiveIntegerField()),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_role_limits', to='accounts.extension')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.specialrole')),
            ],
            options={
                'db_table': 'extension_special_role_limit',
                'constraints': [models.UniqueConstraint(fields=('extension', 'role'), name='uq_extension_role_limit'), models.CheckConstraint(condition=models.Q(('max_count__gt', 0)), name='special_limit_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('account_id__regex', '^[1-9][0-9]{7,}$')), name='app_user_account_id_format'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['super_admin', 'admin']), ('extension__isnull', False), _connector='OR'), name='app_user_extension_required'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email__isnull', True), ('email_verified_at__isnull', True)), models.Q(('email__isnull', False), ('email_verified_at__isnull', False)), _connector='OR'), name='app_user_email_verified_pair'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='app_user_archived_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='uq_app_user_email'),
        ),
        migrations.AddIndex(
            model_name='emailtoken',
            index=models.Index(fields=['user', 'purpose'], name='ix_email_token_user'),
        ),
        migrations.AddConstraint(
            model_name='defaultpassword',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce(models.F('extension'), models.Value(0)), models.F('applies_to_role'), name='uq_default_password'),
        ),
        migrations.AddConstraint(
            model_name='userspecialrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_user_special_role'),
        ),
    ]
