# Generated by Django 6.1.1 on 2026-10-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TithesOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('offering_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('denomination_breakdown', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tithes_offering', to='attendance.attendance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tithes_offering',
            },
        ),
        migrations.CreateModel(
            name='TitheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tithe_entries', to=settings.AUTH_USER_MODEL)),
                ('tithes_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tithes.tithesoffering')),
            ],
            options={
                'db_table': 'tithe_entry',
            },
        ),
        migrations.AddConstraint(
            model_name='tithesoffering',
            constraint=models.CheckConstraint(condition=models.Q(('offering_amount__gte', 0)), name='offering_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='tithesoffering',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='tithes_archived_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='tithesoffering',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('total_amount__isnull', False), _connector='OR'), name='tithes_total_when_not_draft'),
        ),
        migrations.AddConstraint(
            model_name='titheentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='tithe_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='titheentry',
            constraint=models.UniqueConstraint(fields=('tithes_offering', 'user'), name='uq_tithe_entry_user'),
        ),
    ]
