# Generated by Django 6.1.1 on 2026-10-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=20, null=True)),
                ('extension_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, max_length=255, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('system_job', 'System job')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['-created_at'], name='ix_audit_created'), models.Index(fields=['actor_id', '-created_at'], name='ix_audit_actor'), models.Index(fields=['entity_type', 'entity_id'], name='ix_audit_entity'), models.Index(fields=['extension_id', '-created_at'], name='ix_audit_ext')],
            },
        ),
    ]
