# Generated by Django 6.1.1 on 2026-10-05 02:21

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('final_note', models.TextField(blank=True, null=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_rows_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_rows_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_buddy',
            },
        ),
        migrations.CreateModel(
            name='BuddyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='buddy.userbuddy')),
            ],
            options={
                'db_table': 'buddy_note',
            },
        ),
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buddy_request',
                'constraints': [models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='buddy_request_not_self'), models.UniqueConstraint(django.db.models.functions.comparison.Least('from_user', 'to_user'), django.db.models.functions.comparison.Greatest('from_user', 'to_user'), condition=models.Q(('status', 'pending')), name='uq_buddy_request_pending')],
            },
        ),
        migrations.AddConstraint(
            model_name='userbuddy',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='user_buddy_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='userbuddy',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', False), models.Q(('ended_by__isnull', True), ('final_note__isnull', True)), _connector='OR'), name='user_buddy_end_fields'),
        ),
        migrations.AddConstraint(
            model_name='userbuddy',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user_a', 'user_b'), name='uq_user_buddy_active'),
        ),
    ]
