# Generated by Django 6.1.1 on 2026-10-05 02:14

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='streak', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_open_streak', models.PositiveIntegerField(default=0)),
                ('longest_open_streak', models.PositiveIntegerField(default=0)),
                ('last_open_date', models.DateField(blank=True, null=True)),
                ('current_read_streak', models.PositiveIntegerField(default=0)),
                ('longest_read_streak', models.PositiveIntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_streak',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('repeat_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]), blank=True, null=True, size=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('previous_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_goals', to='faith.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='GoalCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('done', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='faith.goal')),
            ],
            options={
                'db_table': 'goal_checkin',
            },
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('opened_app', models.BooleanField(default=False)),
                ('chapters_read', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_activity',
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='ix_goal_user_status'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='goal_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('repeat_type', 'daily'), ('weekdays__isnull', True)), models.Q(('repeat_type', 'weekly'), ('weekdays__isnull', False)), _connector='OR'), name='goal_repeat_matches_weekdays'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='goal_archived_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckin',
            constraint=models.UniqueConstraint(fields=('goal', 'checkin_date'), name='uq_goal_checkin_day'),
        ),
        migrations.AddConstraint(
            model_name='userdailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'activity_date'), name='uq_user_daily_activity'),
        ),
    ]
