# Generated by Django 6.1.1 on 2026-10-05 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_app', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('qr_image', models.ImageField(blank=True, upload_to='donation_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donation_account',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JilVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jil_video',
                'indexes': [models.Index(fields=['-published_at'], name='ix_jil_video_published')],
            },
        ),
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landing_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChurchContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision'), ('core_values', 'Core values'), ('terms', 'Terms'), ('landing_description', 'Landing description')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('fil', 'Filipino')], max_length=3)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'church_content',
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='uq_church_content_key_lang')],
            },
        ),
    ]
