# Generated by Django 6.1.1 on 2026-10-05 02:22

import django.contrib.postgres.fields
import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_action', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notify_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('coordinator', 'Coordinator')], max_length=20), default=notifications.models.default_notify_roles)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_rule',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=60, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True)),
                ('importance', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important')], default='normal', max_length=10)),
                ('audit_log_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['user', '-created_at'], name='ix_notification_user'), models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user', '-created_at'], name='ix_notification_unread')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entity_id__isnull', True), ('entity_type__isnull', True)), models.Q(('entity_id__isnull', False), ('entity_type__isnull', False)), _connector='OR'), name='notification_entity_pair'), models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('user', 'dedupe_key'), name='uq_notification_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preference',
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='uq_notification_pref')],
            },
        ),
    ]
