# Generated by Django 6.1.1 on 2026-10-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='events.event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='accounts.extension'),
        ),
        migrations.AddField(
            model_name='attendancefirsttimer',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_timers', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendancefirsttimer',
            name='converted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['extension', '-attendance_date'], name='ix_attendance_ext_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('extension', 'attendance_date', 'label'), name='uq_attendance_ext_date_label'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='attendance_archived_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancemember',
            constraint=models.UniqueConstraint(fields=('attendance', 'user'), name='uq_attendance_member'),
        ),
    ]
